### ISSUE TITLE
Missing configuration files

### ISSUE THREAD

**Issue by Spl3en** [icon-project/loopchain#3]
I understand this repository is still getting updated actively, but as a feedback from my attempt to install loopchain (without knowing much what I was doing honestly), here's a list of missing files in the current master branch that prevents loopchain from being installed : 
- `resources/default_pki/public.der` and `resources/default_pki/private.der`, but both seem to be correctly created from `create_sign_pki.py` using the old loopchain repository
- `resources/ssl_test_cert/ssl.proto.conf`
- `channel_manage_data.json`
- `package.json`

**Comment by laurenceyoon** [comment]
Our README has been updated. Now you can run the loopchain node.
