### ISSUE TITLE
Console logging using LOG: "console"

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#396]
What is the issue?

When you configure Docker-Compose.yml to pass the LOG: "console" all logs other then 2 logs are put to standard out

booting_xxxx.log
rc.log

The rc.log has very useful information and if you are trying to connect to Fluentd or other external log aggregation engine(stackdriver) it should include this as well.

What should be?

All logs should be put to standard out in container.
```
LOG: "console"
```

**Comment by yakkle** [comment]
stale
