### ISSUE TITLE
Active Passive flag on PREP container for  High Availability deployment

### ISSUE THREAD

**Issue by jerkyrs** [icon-project/loopchain#397]
Currently the HA design that is documented relies on two different containers, one is the Citizen the other the PREP, the PREP is active until it fails at which point pacemaker takes over stopping the Citizen node on standby and starting PREP on the dataset.

Rather then having to maintain both PREP and Citizen node images they could be consolidated into one with the ability to set Active: True and Active: False as environment flag in docker-compose.yml.

If the primary active producer fails the secondary passive mode can be promoted to Active: true, the proposal would be to create a simple protected API endpoint such as /ha=true /ha=false that can be toggled dynamically without a restart of the container. By passing this /ha=true to the instance it begins producing blocks if requested to do so.

This would avoid having two different containers and no need to restart a container on the standby with a different container (citizen --> prep).

**Comment by yakkle** [comment]
stale
