### ISSUE TITLE
Use only "return" or only "yield", not both

### ISSUE THREAD

**Issue by Spl3en** [icon-project/loopchain#40]
https://github.com/icon-project/loopchain/blob/37be39e720021f7b0df46ea6198f9d0f9d450255/loopchain/utils/async/__init__.py#L33-L46

It doesn't make much sense for this generator to return anything - is it working as intended ?

**Comment by zsaladin** [comment]
Hello Spl3en.

I would like to explain why we use both `yield` and `return`.

First of all using both of them is not an abnormal situation.
Codes in a link from python standard library shows that.

More detail.
return statement in generators injects the return value to StopIteration exception. See simple codes below.

More detail.
`return` statement  in generators injects the value returned StopIteration exception. See simple codes below.
```python
def foo():
    yield 1
    return 2

f = foo()
next(f)  # 1
next(f)  # StopIteration: 2
```

More more detail.
That method makes `concurrent.futures.Future` awaitable in async function. `asyncio.Future` will be yielded to event loop. And the event loop detects when the `asyncio.Future`  is completed. Then the event loop resumes the method.

**Comment by zsaladin** [comment]
Hello Spl3en.

I would like to explain why we use both `yield` and `return`.

First of all using both of them is not an abnormal situation.
[Codes in a link](https://github.com/python/cpython/blob/master/Lib/asyncio/futures.py#L254) from python standard library shows that.

More detail.
`return` statement  in generators injects the value returned to StopIteration exception. See simple codes below.
```python
def foo():
    yield 1
    return 2

f = foo()
next(f)  # 1
next(f)  # StopIteration: 2
```

More more detail.
That method makes `concurrent.futures.Future` awaitable in async function. `asyncio.Future` will be yielded to event loop. And the event loop detects when the `asyncio.Future`  is completed. Then the event loop resumes the method. Finally the method will return a result of `concurrent.futures.Future`.

```python
async def run():
     def _long_time_computing():
         print("long_time start")
         time.sleep(5)
         print("long_time end")
         return 10

     print("start")
     executor = futures.ThreadPoolExecutor()
     future = executor.submit(_long_time_computing)  # It is a `concurrent.futures.Future`
     print(await future)
     
loop.run_until_complete(run())
```
Before running the code above you should execute `concurrent_future_monkey_patch` function.

**Comment by Spl3en** [comment]
Oh I see it makes sense, thanks a lot for the explanation ! 🙏
