### ISSUE TITLE
Download mainnet blockchain

### ISSUE THREAD

**Issue by oggy95** [icon-project/loopchain#400]
Hello.
Is there are any link to download all blocks from mainnet blockchain to boost loopchain? Because downloading all blocks via p2p connections will be long.

**Comment by jerkyrs** [comment]
yes there is backup restore that is initiated from starting up PREP, there is also a restore script floating about that also uses these backups provided by foundation to put them into the correct location on your server based on your public IP.

**Comment by tomazcz** [comment]
> 
> 
> Hello.
> Is there are any link to download all blocks from mainnet blockchain to boost loopchain? Because downloading all blocks via p2p connections will be long.

When you set up a citizen/p-rep node, the latest blockchain snapshot is downloaded automatically.

If you need to get to it manually for some reason, you can use this to get its URL:
`echo Download URL: https://s3.ap-northeast-2.amazonaws.com/icon-leveldb-backup/MainctzNet/$(curl -k -s https://s3.ap-northeast-2.amazonaws.com/icon-leveldb-backup/MainctzNet/backup_list | head -n 1)`

**Comment by oggy95** [comment]
> > Hello.
> > Is there are any link to download all blocks from mainnet blockchain to boost loopchain? Because downloading all blocks via p2p connections will be long.
> 
> When you set up a citizen/p-rep node, the latest blockchain snapshot is downloaded automatically.
> 
> If you need to get to it manually for some reason, you can use this to get its URL:
> `echo Download URL: https://s3.ap-northeast-2.amazonaws.com/icon-leveldb-backup/MainctzNet/$(curl -k -s https://s3.ap-northeast-2.amazonaws.com/icon-leveldb-backup/MainctzNet/backup_list | head -n 1)`

I need it not for p-rep node, just for mainnet. Will it be valid?

**Comment by tomazcz** [comment]
> 
> 
> > > Hello.
> > > Is there are any link to download all blocks from mainnet blockchain to boost loopchain? Because downloading all blocks via p2p connections will be long.
> > 
> > 
> > When you set up a citizen/p-rep node, the latest blockchain snapshot is downloaded automatically.
> > If you need to get to it manually for some reason, you can use this to get its URL:
> > `echo Download URL: https://s3.ap-northeast-2.amazonaws.com/icon-leveldb-backup/MainctzNet/$(curl -k -s https://s3.ap-northeast-2.amazonaws.com/icon-leveldb-backup/MainctzNet/backup_list | head -n 1)`
> 
> I need it not for p-rep node, just for mainnet. Will it be valid?

Yes, that is a snapshot of the MainNet blockchain.

**Comment by oggy95** [comment]
Ok, thanks. Close issue.

**Comment by metalg0su** [comment]
@oggy95 @tomazcz 
Hello.
Thanks for your attention on loopchain.

The URL that you wrote on your comment actually provides the MainNet DB snapshot.
As a blockchain, there's no issue in providing DB at public. But I carefully ask you to hide the URL from your comment. Because the storage server is maintained at our own cost. 🔢

**Comment by tomazcz** [comment]
@metalg0su Sure, I removed it from my comments, but @oggy95 needs to redact the quote.

I don't mind mirroring these snapshots on our European server (not s3, that's expensive as you say). Is there a way for that to work and be actually used?

**Comment by metalg0su** [comment]
@tomazcz 
Thank you for accepting my asking.

I agree that the backup server is not well-known endpoint, so the traffic is not at the level of concern.
But the **COST** is possible issue. The server is running and powered by S3 service, which could be a costly in case of spreading the URL (tens of GiB per each download!).

For further questions about this topic, please contact to [Service Desk](https://icon-project.atlassian.net/servicedesk/customer/portal/4)
