### ISSUE TITLE
JSON-RPC IcxTransactionBuilder

### ISSUE THREAD

**Issue by sdpisreddevil** [icon-project/loopchain#561]
I can't sign a transaction using the IcxTransactionBuilder. It appears a white screen after entering the password. 

![Screenshot from 2020-07-23 09-52-47](https://user-images.githubusercontent.com/25897013/88258439-e598ef80-ccdf-11ea-828b-40aa869f54d1.png)
![Screenshot from 2020-07-23 09-54-16](https://user-images.githubusercontent.com/25897013/88258445-e6ca1c80-ccdf-11ea-8baa-20ee31a30606.png)

Source Following: 
https://github.com/icon-project/iconex_chrome_extension/tree/master/docs/iconex_connect

**Comment by yakkle** [comment]
@sdpisreddevil 
You should check first in `iconex_chrome_extension` repo.
I've found that similar [issues](https://github.com/icon-project/iconex_chrome_extension/issues/34) had already been reported.

This issue is closed because it is not related to the `loopchain`.
