### ISSUE TITLE
Can I use solidity to write smart contract in icon network?

### ISSUE THREAD

**Issue by qiluge** [icon-project/loopchain#569]
In the [post](https://medium.com/markusjay/icon-dapps-presentation-by-deblock-part-1-icon-features-roadmap-score-21759c4daaf8), I saw some content that you claim you can support EVM: 
![image](https://user-images.githubusercontent.com/19525062/89248049-4eb62680-d641-11ea-894b-8ea0b74aa7b9.png)
But in your developer portal, I can't see some content about how to use EVM in icon blockchain.

**Comment by yakkle** [comment]
@qiluge 

Short answer is No.

Currently, you can use only python to write SCORE on `ICON` mainnet.
If you want to discuss with members of community, participate [forum](https://forum.icon.community/).

**Comment by qiluge** [comment]
thanks!
