### ISSUE TITLE
Too much memory network usage

### ISSUE THREAD

**Issue by satonz** [icon-project/loopchain#589]
I use docker-compose to start, which takes up too much network and memory

**Comment by satonz** [comment]
this is my docker-compose
version: "3"
services:
   prep:
      image: iconloop/prep-node:latest
      container_name: "prep-mainnet"
      network_mode: host
      restart: "on-failure"
      environment:
         NETWORK_ENV: "mainnet"  # mainnet, testnet, PREP-TestNet (zicon)
         CERT_PATH: "/cert"
         LOOPCHAIN_LOG_LEVEL: "DEBUG"
         ICON_LOG_LEVEL: "DEBUG"
         IS_AUTOGEN_CERT: "true"  # 自动生成证书
         PRIVATE_PASSWORD: "zhjh@1234"  # 证书密码
         FASTEST_START: "yes"   # 加载快照
         TZ: "Asia/Shanghai"   # 时区
      cap_add:
         - SYS_TIME
      volumes:
         - ./data:/data # mount a data volumes
         - ./cert:/cert # Automatically generate cert key files here
      ports:
         - 9000:9000
         - 7100:7100

**Comment by satonz** [comment]
Is it normal for the bandwidth to occupy more than 2M?

**Comment by yakkle** [comment]
I left comment on icondev forum.
https://www.icondev.io/discuss/5fa3b4da7f21b60051a560e5
