### ISSUE TITLE
Can I transfer money to multiple users in one transaction?

### ISSUE THREAD

**Issue by hzccc** [icon-project/loopchain#595]
I want to confirm whether a transaction can only have one transfer. Because I see that JSON-RPC (icx_getTransactionByHash) does not return an array

**Comment by yakkle** [comment]
Please use https://www.icondev.io/discuss in general question.

And, check this community channels.
https://icon.community/resources/links/

**Comment by hzccc** [comment]
> Please use https://www.icondev.io/discuss in general question.
> 
> And, check this community channels.
> https://icon.community/resources/links/

ok
