### ISSUE TITLE
cannot sync block at height 26699

### ISSUE THREAD

**Issue by luomiwhy** [icon-project/loopchain#6]
here is the log out: 

(venv) [admin loopchain]$ ./run_loopchain.sh
remove loopchain.pid
Run loopchain for citizen start!
Run iconservice for citizenstart!
Run iconrpcserver for citizen start!
(venv) [admin loopchain]$ try load configure from json file (./conf/loopchain_conf.json)

0922 13:05:27,004 4867 140048247244608 hx9dcc76  INFO peer_service.py(297) run peer_id : hx9dcc76b626f47126958b7596493c2a8333cb65fd
0922 13:05:29,310 4867 140047896110848 hx9dcc76  INFO grpc_helper.py(55) Server now listen: [::]:7100, secure level : SSLAuthType.none
0922 13:05:29,313 4867 140047896110848 hx9dcc76  INFO grpc_helper.py(55) Server now listen: 127.0.0.1:17100, secure level : SSLAuthType.none
0922 13:05:29,313 4867 140047896110848 hx9dcc76  INFO common_service.py(74) CommonService is running
0922 13:05:29,315 4867 140048247244608 hx9dcc76  INFO peer_service.py(374) Start Peer Service at port: 7100 start duration(2.3438023030757904)
try load configure from json file (./conf/loopchain_conf.json)
0922 13:05:30,154 4899 140566458439488  icon_dex INFO channel_service.py(67) ChannelService : icon_dex, Queue : Channel.icon_dex.7100
0922 13:05:30,204 4899 140566119995136 hx9dcc76 icon_dex INFO block_manager.py(689) channel(icon_dex) Block Manager thread Start.
0922 13:05:30,206 4899 140565890987776 hx9dcc76 icon_dex INFO grpc_helper.py(76) Client Channel : 10.200.172.129:7100, secure level : SSLAuthType.none
0922 13:05:30,238 4899 140566458439488 hx9dcc76 icon_dex INFO blockchain.py(126) re-build transaction count from DB....
0922 13:05:30,238 4899 140566458439488 hx9dcc76 icon_dex INFO blockchain.py(141) rebuilt blocks, total_tx: 1242244
0922 13:05:30,238 4899 140566458439488 hx9dcc76 icon_dex INFO blockchain.py(142) block hash(4386417d95b1ff4afc2d5010df2659486ef38f8d4e5dcec37b7f6b0b0f684479) and height(26699)
0922 13:05:30,238 4899 140566458439488 hx9dcc76 icon_dex ERROR peer_manager.py(798) there is no peer by id: hx9dcc76b626f47126958b7596493c2a8333cb65fd
0922 13:05:30,240 4867 140048247244608 hx9dcc76  INFO peer_service.py(386) peer_service: init complete peer: hx9dcc76b626f47126958b7596493c2a8333cb65fd
0922 13:05:30,248 4899 140565874202368 hx9dcc76 icon_dex INFO block_manager.py(481) try block height sync...with love&hate
0922 13:05:30,248 4899 140565874202368 hx9dcc76 icon_dex INFO grpc_helper.py(76) Client Channel : test-ctz.solidwallet.io:443, secure level : SSLAuthType.none
0922 13:05:30,909 4899 140565874202368 hx9dcc76 icon_dex INFO block_manager.py(498) You need block height sync to: 30787 yours: 26699
cx795a665e55aa1b3ff22e837f1bd86f9d68a23321 hxd5775948cb745525d28ec8c1f0c84d73b38c78d4 100000000000000000000
_**0922 13:05:33,676 4899 140565874202368 hx9dcc76 icon_dex ERROR __init__.py(90) Service Stop by add_block FAIL commit state integrity!! This Peer will Down.
NoneType: None**_

(venv) [admin loopchain]$
(venv) [admin loopchain]$ ll -h log/*
-rw-rw-r-- 1 admin admin  918 Sep 22 13:05 log/iconrpcserver.log
-rw-rw-r-- 1 admin admin    0 Sep 22 13:01 log/iconservice.log

log/exc:
total 0
-rw-rw-r-- 1 admin admin 0 Sep 22 13:01 iconrpcserver.log
-rw-rw-r-- 1 admin admin 0 Sep 22 13:01 iconservice.log
(venv) [admin loopchain]$

**Comment by luomiwhy** [comment]
connet node：

Node | https://test-ctz.solidwallet.io

**Comment by yakkle** [comment]
@luomiwhy 
It work correctly now.
Issue occurred because of icon service has trouble when invoke score.
[icon-service](https://github.com/icon-project/icon-service) and [icon-rpc-server](https://github.com/icon-project/icon-rpc-server) fixed and now updated.

re-install icon-service and icon-prc-server then retry sync.
```
$ pip3 install --force-reinstall git+https://github.com/icon-project/icon-service.git
$ pip3 install --force-reinstall git+https://github.com/icon-project/icon-rpc-server.git
```

**Comment by yakkle** [comment]
I have confirmed sync completed with https://test-ctz.solidwallet.io.
