### ISSUE TITLE
What is the transaction model?

### ISSUE THREAD

**Issue by hskang9** [icon-project/loopchain#7]
Is it utxo or account-balance? If it is neither of those, why is it used?
Is there any wiki or document to look up the opcodes for SCORE or is the smart contract language just based on Python virtual machine?

**Comment by goldworm-icon** [comment]
Thanks for your interest on icon.
icon is based on account-balance like ethereum.

If you are interested in developing a smart contract, please refer to the document below
https://github.com/icon-project/icon-service/blob/develop/docs/dapp_guide.md

"icon-service" is the platform which a smart contract runs on

**Comment by hskang9** [comment]
I **do not** think it is like Ethereum. First, I see that you guys are using [transition](https://github.com/pytransitions/transitions) library to build statemachine instead of connecting to Trie database, and I have list of questions other than that.
- Where's the `statehash` which is used for verifying the state on each block just as bitcoin and ethereum does? 
- Do you finalize the state on Consensus algorithm? or do you verify the user's state after traversing through each block's data? 
- Does the state even guarantee that the record will be stored in a separate space so that it can be recovered even when the node is shut down? 
- Where is the embedded Database which stores the user's state other than the blocks? 
- Where are the state transition function(STF)s for managing user's transactions and minting coins to miner?
-  How is the smart contract account data model formed? 
-  Do they have a `code` property which stores the compiled hex data on deployment? 
- Where is the [opcodes](https://github.com/ethereum/pyethereum/blob/develop/ethereum/opcodes.py) file to map transaction `raw_data` from transaction to decode in [virtual machine](https://github.com/ethereum/pyethereum/blob/develop/ethereum/vm.py)? Do you run smart contracts on a centralized server? If not, where is the node which runs those contracts and what are the rewards and economics?
- Why does a `Transaction` object have a `nonce` property whereas ethereum has it on`Account`?
- What is this node's status between citizen and the board?
- Where is the wiki of nodes which describes the hierarchy between them?
- So if I make a SCORE contract, where does it go, and how is it compiled? Is SCORElang open-source?
- By far I do not see any state transition functions in this node's consensus library. How does this participate in the node ecosystem?
- Do you have a yellow paper for explaining all of these above?

I feel pretty sure that loopchain has some different approaches with the hierarchy of different nodes, but there are a lot of things that are not explained yet.
